INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (1,'rdiet St.',642,325,'Ulster','GA','3473F');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (2,'P.O.Nulla St.',518,502,'AZ','Ankara','6176');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (3,'Ap Donec Road',998,610,'SP','Vienna','9461H');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (4,'P.O.itae St.',16,251,'IM','Oost-Vlaanderen','03545');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (5,'St.',154,627,'Vienna','MetropolitanSantiago','05394');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (6,'Ap Lorem St.',669,318,'Illes Balears','Balıkesir','8490N');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (7,'Duis Road',738,634,'Queensland','L','18397');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (8,'a Av.',166,267,'ON','Ulster','53963');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (9,'Ap Leo. Road',183,974,'NO','O','03923');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (10,' Street',97,676,'İzm','West-Vlaanderen','27492');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (11,'Ut, Street',96,887,'Queensland','Leinster','7677Z');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (12,'Ipsum Ave',896,739,'TN','Emilia-Romagna','88133');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (13,'P.O.In, St.',292,206,'Oo.','Goias','20433');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (14,'Ap Pharetra, St.',858,716,'CT','Sicilia','21415');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (15,'Varius. Rd.',421,947,'Sicilia','SIC','78161');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (16,'Ap Convallis, St.',272,998,'Maule','Henegouwen','96123');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (17,'Ap Dolor Avenue',729,348,'AG','North Island','20812');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (18,'P.O.Etiam Ave',913,101,'Alaska','KT','7434I');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (19,'Pox Lacus. Road',193,795,'Georgia','Provence-Alpes Azur','7154');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (20,'Ap Ac Rd.',373,129,'C','Bihar','49039');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (21,'P.O.Urna St.',727,470,'Berlin','Andhra Pradesh','45052');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (22,'am Street',591,411,'Wielkopolskie','MAR','A40EL');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (23,'Ap Suscipit, St.',772,913,'Pembrokeshire','North Island','4663');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (24,'Tempor Av.',101,677,'ON','CN','9294');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (25,'Ap Semper, Rd.',388,428,'North Island','Bremen','1359B');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (26,'Diam. Rd.',512,87,'Victoria','Lazio','16411');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (27,'s. Avenue',162,882,'Antalya','SI','30691');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (28,'Ap In Rd.',358,269,'NI','Aragon','3793G');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (29,'P.O.Non Street',243,895,'Pomorskie','VII','29090');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (30,'. Road',56,449,'Madrid','Bremen','D96JO');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (31,'P.O.Proin St.',59,890,'OP','SP','05544');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (32,'Ap Nec Road',896,756,'Tennessee','LIG','79264');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (33,'tas Rd.',979,95,'Lubuskie','Benue','7032');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (34,'. Street',565,785,'Missouri','Baden','45917');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (35,'s. Road',543,757,'Victoria','Piemonte','70713');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (36,'P.O.Odio, Street',361,74,'Quebec','DE','68249');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (37,'Vivamus Ave',15,227,'Connacht','NI','75831');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (38,'Aliquam Rd.',890,364,'Connecticut','British Columbia','2684');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (39,'Quam. Rd.',55,865,'X','WB','06746');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (40,'Ap Id, Street',588,71,'North Island','Comunitat Valenciana','GP1T6');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (41,'Mi St.',841,538,'Luxemburg','ON','73136');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (42,'m Av.',801,848,'São Paulo','Ontario','1368');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (43,'P.O.Mi St.',765,91,'Ontario','Campania','25455');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (44,'P.O.A St.',713,932,'ON','Wie','24317');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (45,'Mauris Av.',851,480,'IA','Vlaams-Brabant','50370');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (46,'get, Av.',244,656,'TAS','Schleswig-Holstein','2413');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (47,'P.O.Scelerisque Av.',734,778,'OG','RM','26622');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (48,'P.O.dipiscing Rd.',766,936,'CH','PR','14476');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (49,'P.O.Turpis St.',841,657,'CO','VII','C43KW');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (50,' Rd.',570,209,'Delta','X','10219');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (51,'Road',107,191,'Wie','Gaz','40850');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (52,'r, Street',713,901,'BU','TN','49128');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (53,'t.',346,130,'AB','Vienna','3212');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (54,'Ap Nunc Ave',503,117,'RM','Queensland','96994');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (55,'P.O.Ultricies Ave',500,893,'MetropolitanSantiago','Nottinghamshire','16621');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (56,'P.O.Quisque Avenue',476,828,'N.','IL','40277');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (57,'is. Street',948,416,'QC','RM','4228');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (58,'Ap rcu Road',368,971,'SP','North Island','75');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (59,'v.',149,914,'SP','Wyoming','4257');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (60,'er Avenue',390,280,'NI','Sicilia','33591');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (61,'Ap Arcu. Street',484,360,'Ist','İzm','44015');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (62,'Ap Sit Road',841,340,'Andalucia','SJ','70164');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (63,'Ap Consequat St.',605,756,'Wie','Bur','29731');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (64,'m Avenue',752,805,'NI','HH','88778');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (65,'d.',672,473,'AK','DS','2419');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (66,'m. Road',799,35,'Heredia','San Jose','35193');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (67,'Ave',58,476,'C','HH','63163');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (68,'P.O.Egestas. Road',267,158,'łodzkie','BC','51422');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (69,'Ap Metus Rd.',188,172,'SJ','NI','54467');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (70,'Ap Malesuada Av.',99,166,'North Island','OR','33747');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (71,'bitur Rd.',587,224,'İzm','AN','F91VU');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (72,'d.',510,408,'Saarland','Stockholms lan','65733');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (73,'Ap Arcu. Rd.',352,259,'Lombardia','Vienna','91762');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (74,'P.O.Nonummy Road',817,957,'California','Yukon','VY0T5');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (75,'P.O.Fermentum St.',787,72,'III','VIC','19473');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (76,'Ap Ipsum St.',587,584,'VI','UT','67892');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (77,'Ap Sed Street',329,69,'Munster','BC','R55AG');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (78,'t Street',746,218,'BE','Veneto','63');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (79,'P.O.Lorem Ave',670,799,'Gavleborgs lan','BE','82165');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (80,' Rd.',578,852,'South Island','Leinster','69804');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (81,'Rutrum Street',714,408,'AB','BE','66387');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (82,'or Av.',400,571,'SIC','F','79584');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (83,'Ap Sit Street',350,364,'Wie','FVG','7747');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (84,'Ap In Rd.',510,693,'Toscana','Kansas','75152');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (85,'Ac, St.',780,795,'CT','Manitoba','4238');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (86,' Avenue',614,886,'Namen','Ist','11108');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (87,'Ap Et St.',951,938,'Leinster','Bremen','S36RY');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (88,'. St.',554,565,'Wie','ON','80715');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (89,'P.O.Purus, Rd.',625,1000,'MP','Montana','13564');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (90,'Ap Erat Road',856,312,'BE','QC','7118');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (91,'Sapien. Ave',15,975,'AG','Stockholms lan','95243');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (92,'Eu, St.',119,737,'Gaz','Georgia','49614');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (93,'tis. Road',551,600,'KY','PR','75719');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (94,'Ap Molestie Rd.',674,435,'Ulster','Pennsylvania','5992T');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (95,'ntum Avenue',658,845,'Ontario','Cumberland','34881');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (96,'Rutrum Ave',777,585,'Vienna','C','4230');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (97,'Pox Integer Rd.',982,118,'KS','NSW','81979');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (98,'am Av.',482,946,'L','WM','10262');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (99,'rtis Rd.',491,645,'Arizona','Kahramanmaraş','YK4G3');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (100,'on St.',154,393,'Bihar','Henegouwen','74024');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (101,'Ap Nonummy Street',39,116,'Bursa','Dolnośląskie','37693');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (102,'Ap urpis Rd.',162,297,'Istanbul','CT','31926');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (103,'ve',375,755,'NA','IL','93863');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (104,'P.O.Montes, Street',655,889,'Devon','L','61315');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (105,'Odio St.',881,339,'Piemonte','Wie','1102');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (106,'P.O.Quisque Road',952,707,'Stockholms lan','North Island','42794');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (107,'Metus St.',252,593,'VIC','Drenthe','38218');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (108,'P.O.Faucibus. Ave',825,651,'Quebec','Maranhão','88497');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (109,'gilla, Rd.',453,400,'AN','Luik','F83TE');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (110,'P.O.Mauris St.',24,12,'VIC','Victoria','92791');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (111,'Ap Sed Rd.',940,523,'CA','Pays de la Loire','73869');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (112,'Est Road',935,493,'Alajuela','Haryana','11845');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (113,'Nunc Road',219,58,'Galicia','RM','26122');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (114,'Ap A, Road',560,323,'Ist','Alaska','RR9R6');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (115,'Box Eget Street',66,710,'IX','West Bengal','1220');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (116,'Ap Dolor St.',449,774,'Ontario','Luik','16488');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (117,'Ap Neque. Av.',224,558,'Oo.','Sicilia','17518');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (118,'Ap Donec Rd.',460,764,'IX','Utah','14096');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (119,'P.O.Quis St.',535,732,'C','Carinthia','2868');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (120,'Rd.',601,799,'Antwerpen','Bremen','1947F');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (121,'Mauris St.',515,921,'LOM','Bihar','22027');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (122,'Orci, St.',273,331,'Stm','British Columbia','67435');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (123,'umsan Rd.',142,245,'PI','Victoria','9822');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (124,'P.O.Lacus. Av.',384,583,'Washington','PB','21143');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (125,'Rd.',694,521,'Kano','NI','47787');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (126,'Eu, St.',32,29,'Ontario','Louisiana','Z89GP');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (127,'P.O.Non, Rd.',496,888,'O','Gl','82729');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (128,'am Rd.',239,192,'Staffordshire','Zeeland','21506');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (129,'Ap Dui. Av.',23,384,'FL','Antalya','90351');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (130,'Amet Rd.',976,302,'Canarias','VIC','47625');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (131,'e. St.',40,54,'Marche','QLD','07642');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (132,'P.O.ellus Avenue',711,422,'UP','QC','51969');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (133,'P.O.Egestas. Avenue',111,491,'Ist','RJ','5113');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (134,'Box Dui. Street',309,555,'U','Cartago','90997');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (135,'Ap Quisque Ave',592,752,'VB','IM','3734');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (136,'Id Av.',249,165,'Alberta','VIC','5174');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (137,'Ap Nec St.',368,746,'Guanacaste','AN','74101');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (138,'s Avenue',37,641,'Iowa','Jonkopings lan','2619');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (139,'Lectus Street',361,385,'SP','Vienna','45784');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (140,' Rd.',896,578,'SC','Diyarbakır','51');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (141,'P.O.Eget, Rd.',74,953,'Vienna','ile-de-France','2069');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (142,'.Adipiscing Street',979,253,'Guanacaste','WB','4586');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (143,'Ap Non Road',121,98,'DS','Flintshire','13372');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (144,'Ap Vel Av.',338,895,'Indiana','Uttar Pradesh','86549');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (145,'P.O.Sit Rd.',444,410,'MA','Piemonte','48');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (146,'Ap Imperdiet Ave',551,247,'OR','Zeeland','52049');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (147,'Ap Est, Av.',645,730,'North Westphalia','Sląskie','90498');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (148,'Enim. Road',830,287,'Minas Gerais','QLD','70177');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (149,'Non Road',208,582,'Galicia','Wie','9577');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (150,'tibus St.',509,468,'QC','Namen','2953');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (151,'Et Rd.',389,729,'Dr','Valparaiso','13755');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (152,'P.O.Enim. Street',892,545,'NT','UP','3474');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (153,'Box Aliquam Ave',617,230,'Vienna','Nairnshire','1066');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (154,'Montes, St.',986,237,'VT','Waals-Brabant','35');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (155,'Ap Sem Avenue',561,385,'BE','South Island','8408');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (156,'St.',715,713,'Arkansas','Andalucia','71021');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (157,' St.',298,916,'OV','Maranhão','7861N');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (158,'Et, Av.',321,520,'NW','AN','34224');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (159,'Ap tiam Rd.',857,905,'lodzkie','SP','RS2M8');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (160,'or. St.',922,511,'Hampshire','Lagos','42617');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (161,'P.O.Nulla Road',365,897,'Henegouwen','BE','6454W');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (162,' Av.',507,761,'Rio Grande do Sul','Wie','8156');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (163,'Avenue',36,148,'Katsina','HB','5732V');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (164,'P.O.Eu, Road',4,929,'SA','Uttar Pradesh','4747');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (165,'P.O.Mauris Street',828,783,'Brussels fdstedelijk','AN','WF1SD');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (166,'Massa St.',893,130,'Comunitat Valenciana','Sląskie','87633');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (167,'u. Avenue',903,332,'Mer','NA','5954');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (168,'Ap Cras Road',159,89,'Illes Balears','Stockholms lan','81367');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (169,'Ap ascetur Av.',988,134,'RJ','Alajuela','6213');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (170,'uam Avenue',519,67,'Alsace','MG','99230');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (171,'etuer Rd.',502,229,'OR','Minas Gerais','2395');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (172,'Ap Congue Rd.',9,405,'Ontario','ID','NG3Y8');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (173,'Ap Erat Av.',339,160,'MV','British Columbia','6599');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (174,'P.O.Ipsum. St.',702,71,'Istanbul','LOM','14955');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (175,'Ap Feugiat Rd.',498,658,'Murcia','SJ','37442');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (176,'Box Tellus. St.',387,270,'SI','Jonkopings lan','84266');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (177,'A, St.',699,460,'F','Berlin','02');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (178,'Ante, St.',390,932,'Mazowieckie','NW','8548');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (179,'Fermentum St.',206,216,'Antalya','CT','44272');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (180,'r. St.',553,689,'ON','ON','03309');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (181,'ignissim Street',314,812,'F','C','46344');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (182,'Ap Eget Av.',687,168,'ON','Istanbul','64130');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (183,'P.O.Lectus Av.',623,347,'Wielkopolskie','Vienna','5695');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (184,'Ap Augue St.',50,623,'ON','SJ','09474');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (185,'Purus, Rd.',929,210,'ON','Podkarpackie','50006');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (186,'Sed Avenue',792,16,'Kano','AL','9700');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (187,'Fusce Road',853,707,'North Island','PM','8323B');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (188,'Feugiat. Street',937,39,'ZP','Mazowieckie','00807');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (189,'Ap Donec Street',75,372,'ON','Jonkopings lan','31306');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (190,'Ap Mi Rd.',637,226,'LA','Nebraska','35907');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (191,'lis, Av.',268,421,'Cartago','ON','19074');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (192,'urient Road',945,940,'CT','OR','53052');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (193,'Ap Mattis St.',166,404,'Franche-Comte','SP','9324C');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (194,'P.O.aecenas Road',398,580,'MB','Castilla y Leon','60103');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (195,'Ap Lobortis St.',215,931,'HA','PM','2577');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (196,'Libero. Ave',138,114,'San Jose','AN','63738');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (197,'ellus Road',826,920,'Rivers','South Island','07591');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (198,'ibus Rd.',384,597,'Vienna','Wyoming','57262');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (199,'Ap Metus. Road',928,867,'Los Rios','N.','92434');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (200,'Ap Duis Avenue',13,883,'San Jose','Madrid','7989');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (201,'P.O.Dui, Av.',906,157,'North Island','NB','06038');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (202,'P.O.Neque Road',246,124,'Berlin','CT','95865');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (203,'t.',675,829,'Ontario','LA','21447');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (204,'Vel Avenue',577,337,'North Island','U','68063');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (205,'endisse St.',542,136,'Wie','Dalarnas lan','40560');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (206,'tum. Road',972,75,'Western Australia','BA','82202');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (207,'Ap Urna. Ave',625,266,'Catalunya','AN','73262');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (208,'P.O.Vestibulum. Rd.',894,70,'Madhya Pradesh','Pomorskie','7055');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (209,'Box Libero. Av.',593,169,'Rio de Janeiro','ON','61846');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (210,'s Rd.',893,85,'Quebec','North Island','86885');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (211,'P.O.Viverra. Ave',682,101,'AB','ERM','55749');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (212,'Box Mauris. Rd.',294,709,'AN','West Bengal','71966');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (213,'us. Rd.',391,726,'SJ','West-Vlaanderen','2279K');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (214,'Ap Mi Av.',527,867,'NI','LB','52576');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (215,'Augue, Road',776,250,'LK','Ontario','87120');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (216,'Rd.',168,84,'Şanlıurfa','C','7097');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (217,'um Rd.',461,864,'NB','GL','9252');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (218,' Av.',922,725,'ile-de-France','RI','02319');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (219,'s Av.',228,858,'Ktn','RM','16020');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (220,'a Ave',923,92,'Connacht','ON','4045');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (221,'in Av.',30,204,'Bursa','Kocaeli','36023');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (222,'Ap Tellus Rd.',210,357,'AQ','Odisha','88997');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (223,'Ap Quis Street',126,5,'Małopolskie','N.','51309');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (224,'P.O.Vitae Avenue',254,248,'Nebraska','La Rioja','50526');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (225,'. St.',905,86,'Maharastra','Yorkshire','42918');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (226,'. Av.',195,883,'Rivers','Leinster','85114');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (227,'Av.',57,802,'Bremen','U','00486');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (228,'Eu Road',558,903,'Ontario','ON','44515');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (229,'Ap Gravida Road',810,395,'C','Uttar Pradesh','7076');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (230,'Ap Porttitor St.',449,463,'C','Małopolskie','35109');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (231,'mus Road',367,327,'Sląskie','Cartago','57120');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (232,'Box Cras Avenue',888,628,'Munster','Vorarlberg','11113');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (233,'stie Street',680,230,'Nord-Pas-de-Calais','Haute-Normandie','5584');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (234,'Ap Non Road',147,513,'VB','G','94042');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (235,'Etiam St.',743,943,'AN','Provence-Alpes-Azur','92566');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (236,'P.O.Vulputate Avenue',928,952,'Stockholms lan','PIE','94431');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (237,'Ap Amet, Road',340,666,'Alsace','Istanbul','96359');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (238,'Est Avenue',89,159,'ST','F','63264');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (239,'St.',485,794,'Antwerpen','Luxemburg','94251');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (240,'Ap Etiam Street',496,547,'Pomorskie','Shropshire','04532');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (241,'Road',905,794,'Leinster','PE','23654');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (242,'Ap Id Road',173,831,'Kano','Stockholms lan','56101');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (243,'Cras Rd.',922,981,'OV','Luxemburg','15531');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (244,'P.O.Eget Rd.',247,245,'RU','CA','18756');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (245,'Nisl. Rd.',558,591,'Vienna','QLD','41522');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (246,'Ligula. Rd.',193,529,'PV','F','E02RX');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (247,'Box Nunc Street',308,954,'CA','UT','73926');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (248,'etra. Road',204,525,'Assam','Kansas','BD8DX');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (249,'Blandit Rd.',275,481,'HA','North Island','57681');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (250,'eo. Avenue',106,285,'łodzkie','Tarapaca','20543');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (251,'P.O.Duis Av.',585,74,'Catalunya','Istanbul','57469');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (252,'P.O.nim, Rd.',405,305,'C','Provence-Alpes-Azur','48');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (253,'Ap Cursus Rd.',19,733,'Gelderland','Manitoba','20');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (254,'Ap Nunc Ave',534,405,'Minas Gerais','Parana','00051');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (255,'Sapien. St.',521,436,'Kujawsko-pomorskie','BC','6069');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (256,' Rd.',189,503,'SP','Anambra','19560');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (257,'Ap nte Av.',111,50,'Kon','C','MC5A4');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (258,'Lacus. Av.',375,857,'L.','LU','YG9J3');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (259,'P.O.Molestie St.',660,71,'Wielkopolskie','RS','7012');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (260,'Ac St.',163,52,'IX','BE','58104');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (261,'t.',605,493,'Washington','Valparaiso','76205');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (262,'P.O.Ut Rd.',643,918,'RJ','Maine','32360');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (263,'Ap Suspendisse Road',998,143,'C','Alberta','8741');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (264,'Ap Pede. Road',39,856,'Munster','HB','90759');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (265,'Sed, St.',730,969,'Cartago','Warmińsko-mazurskie','81178');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (266,'uam Ave',553,194,'LOM','RM','45888');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (267,'uet, Av.',993,377,'E','LX','4723');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (268,'Ap Sagittis Av.',770,307,'Lorraine','Kano','41560');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (269,'Tortor Rd.',95,30,'BC','MetropolitanSantiago','04861');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (270,'P.O.Pede, Road',153,944,'New South Wales','ZP','52365');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (271,'Eget Avenue',584,969,'Ov','Ontario','16302');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (272,'Felis Rd.',630,863,'Namen','CAM','9363');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (273,'P.O.Id, Road',62,784,'North Island','DS','D37TN');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (274,'Leo. Ave',729,503,'Hawaii','KY','6144');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (275,'Sit Street',500,893,'Emilia-Romagna','North Island','6191');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (276,'Et St.',176,448,'CA','NA','38554');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (277,'ttis St.',321,543,'Ontario','Bavaria','0894D');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (278,'P.O.Facilisis St.',187,740,'HB','Berkshire','4550');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (279,'is. Avenue',45,677,'Munster','UP','28921');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (280,'Ut Rd.',75,40,'KD','Kano','XK5S5');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (281,'or Rd.',491,507,'Wielkopolskie','Ontario','5474');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (282,'in Av.',572,365,'Kentucky','AB','42642');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (283,'Ap Vulputate St.',725,132,'Sicilia','BE','53574');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (284,' St.',50,379,'Vlaams-Brabant','Gujarat','3925');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (285,'ibus Av.',309,347,'L','BR','10170');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (286,'P.O.Risus Av.',58,137,'Provence-Alpes-Cote','Munster','2377');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (287,'a. St.',56,69,'South Australia','AU','24584');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (288,'P.O.Fringilla Avenue',57,445,'HI','ON','48898');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (289,'imentum. Road',259,202,'SF','MD','22740');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (290,'P.O.Sed St.',237,899,'Cornwall','Quebec','99828');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (291,'P.O.Curabitur Av.',88,45,'Ontario','PD','38768');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (292,'Ap Nunc Av.',124,831,'Cantabria','WA','43044');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (293,'P.O.Ultricies Rd.',877,976,'Adana','Maharastra','61');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (294,'. Ave',307,997,'Ada','Şanlıurfa','85535');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (295,'uet Av.',995,85,'Quebec','BE','1705');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (296,'Ap Sed, Rd.',281,706,'Brussels fdstedelijk','Abruzzo','88198');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (297,'gilla St.',366,674,'Wie','Iowa','7882F');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (298,' St.',42,202,'GO','SO','10101');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (299,'ue Street',363,969,'PIE','Oost-Vlaanderen','BG2J0');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (300,'Ligula. Rd.',982,604,'W','Vienna','36686');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (301,'or. Street',306,716,'łodzkie','Durham','53541');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (302,'P.O.Nec, Road',107,693,'Aquitaine','Berlin','58168');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (303,'Ap Pharetra, St.',666,917,'AN','A','87');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (304,'Ap Mauris Street',295,997,'South Island','Victoria','69844');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (305,'ger Street',423,542,'Texas','VEN','3722');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (306,'P.O.Lacus. St.',288,196,'Alberta','Rajasthan','EP3FL');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (307,'Ap Eleifend Ave',388,889,'Balıkesir','C','1433');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (308,' Rd.',150,413,'Missouri','PUG','82542');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (309,'Sit St.',720,442,'Flevoland','IL','33017');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (310,'Nibh Avenue',461,208,'Victoria','New Brunswick','09753');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (311,'Elit. Ave',277,505,'Victoria','N.','28569');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (312,'Ap Magna. Street',21,657,'MetropolitanSantiago','PE','1671');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (313,'ulis Road',853,113,'AS','Catalunya','6722');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (314,'Ap Litora Avenue',384,455,'Istanbul','OP','TI2TA');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (315,'Ap Quis, Rd.',328,964,'Luik','Uttar Pradesh','3402');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (316,'iscing Av.',646,596,'FI','Alsace','25184');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (317,'Ap Diam St.',468,391,'KN','Maharastra','89144');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (318,'P.O.lit Rd.',596,825,'San Jose','Luik','00628');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (319,'Avenue',562,645,'Madrid','Oyo','62401');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (320,'uet Road',280,220,'Kincardineshire','South Island','2682F');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (321,'m, St.',572,496,'Auvergne','AN','17623');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (322,'P.O.Nam Av.',935,594,'VB','Saxony-Anhalt','15265');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (323,'Ap Egestas St.',537,213,'Ulster','Valparaiso','15933');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (324,'erisque Rd.',594,912,'British Columbia','Queensland','48968');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (325,'lisi. Road',885,656,'KT','SC','16199');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (326,'Nunc St.',44,115,'PR','South Island','05070');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (327,'. Rd.',623,850,'UP','KD','74210');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (328,'s Avenue',923,522,'Saskatchewan','Vienna','13918');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (329,'P.O.Curabitur St.',727,133,'Lagos','Wie','95092');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (330,'P.O.Vel Ave',9,144,'MetropolitanSantiago','Bahia','1528');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (331,'Ap Vel Road',612,286,'BA','CA','11377');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (332,'Street',206,676,'SN','Victoria','55448');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (333,'titor Rd.',921,265,'Utah','L','9019');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (334,'Placerat Avenue',759,883,'CV','Ist','8558');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (335,'Ap Dui St.',202,865,'Ontario','Ist','40103');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (336,'Box Lectus Road',467,903,'LI','Ontario','76818');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (337,'us Av.',255,298,'Bal','Veneto','57082');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (338,'Sed, Ave',317,522,'BC','Hamburg','40900');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (339,'. Avenue',14,438,'Victoria','ON','O25FQ');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (340,'Ap Dictum. Av.',711,108,'M','Ontario','36648');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (341,'Ap Ipsum. Ave',25,577,'San Jose','Ceara','68113');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (342,'Ap Tempus Av.',198,982,'U.','Kano','20708');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (343,'Ap Quis St.',891,414,'Connacht','BR','PP8Y9');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (344,'cerat Rd.',568,867,'AR','Vienna','6617');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (345,'itudin Avenue',468,345,'DE','Istanbul','99020');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (346,'Box Montes, Rd.',164,676,'Rio de Janeiro','Munster','19130');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (347,'Ap Nunc. St.',508,101,'Berlin','BU','6474B');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (348,'Box Integer Rd.',910,385,'Berlin','WI','30205');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (349,'P.O.Lobortis. St.',496,873,'Munster','ile-de-France','YV2LH');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (350,'or. St.',29,819,'LAZ','Lazio','95282');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (351,'Box Cras Street',1000,175,'O','BC','67231');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (352,'is. Av.',58,714,'New South Wales','LD','LB7FT');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (353,'Semper Rd.',130,667,'Noord Brabant','QC','6556');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (354,'Box Sapien, St.',648,673,'II','Maryland','99005');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (355,'Commodo St.',618,349,'MAR','OK','5497');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (356,'P.O.Vel Avenue',646,328,'WV','MG','QA0EO');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (357,'Blandit St.',402,601,'Dalarnas lan','Wie','1360');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (358,'Ap isus. Ave',754,715,'Mazowieckie','Ontario','59239');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (359,'P.O.Dictum Street',101,835,'Wie','Alberta','53748');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (360,'Ap Id St.',66,852,'BE','CAM','25036');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (361,'Ap Rutrum Av.',475,530,'Kon','P','93');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (362,'Ap Vehicula Street',427,627,'Araucania','Sam','09429');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (363,'ue St.',623,347,'Sląskie','AK','8001');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (364,'P.O.Feugiat Street',462,366,'Gl','NI','02884');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (365,'Scelerisque Street',800,926,'Victoria','Maharastra','15001');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (366,'Cubilia Ave',767,721,'Man','H','16');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (367,'Est Road',175,238,'Coquimbo','Vienna','69363');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (368,'e Ave',607,402,'Vastra Gotalands lan','Victoria','36392');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (369,'Ap Diam St.',413,640,'VA','Bihar','77388');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (370,'P.O.Risus. St.',979,592,'Alajuela','SL','41393');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (371,'Ave',942,834,'Lazio','Ontario','8270');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (372,'Ap Aenean Ave',111,268,'OV','ON','79896');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (373,'Lorem Ave',486,624,'YK','Vienna','18709');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (374,'utate Rd.',267,158,'N.','Berlin','21888');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (375,'a. Av.',123,926,'N.','West-Vlaanderen','58822');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (376,'re Street',243,852,'QC','Antwerpen','9183');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (377,'P.O.igula. St.',238,715,'İzm','Sląskie','61715');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (378,'Ap ravida. St.',145,508,'Hatay','Uttar Pradesh','25136');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (379,'P.O.Duis St.',89,760,'WP','Queensland','87');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (380,'Ap ec Ave',208,569,'Bur','SJ','4680');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (381,'mod Ave',683,237,'OR','F','92430');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (382,'St.',415,913,'Vastra Gotalands lan','Comunitat Valenciana','01129');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (383,'P.O.Lorem Rd.',444,769,'BK','Kansas','27643');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (384,'Box Diam Street',381,151,'HR','VII','79335');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (385,'P.O.Adipiscing Road',684,171,'Andalucia','Gelderland','44549');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (386,'ro. Avenue',476,288,'MO','WP','8456');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (387,'. St.',853,69,'LD','Valparaiso','49');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (388,'rdiet St.',981,326,'ile-de-France','North Island','22');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (389,'P.O.ec St.',171,369,'Vienna','ABR','EW0K7');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (390,'Box Sapien, Rd.',18,770,'North Island','Catalunya','17700');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (391,'e, Rd.',451,830,'Limon','O','72549');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (392,'Box Nec, Street',536,777,'CA','PE','02913');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (393,'. Avenue',371,43,'Poitou-Charentes','Rio de Janeiro','JA0A0');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (394,'Ap Lorem Rd.',184,934,'SI','P','56');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (395,'suada Rd.',687,301,'Stockholms lan','Auvergne','3414');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (396,'P.O.Aenean Avenue',142,440,'Assam','TOS','7765');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (397,' Street',230,38,'Oost-Vlaanderen','San Jose','00792');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (398,'i Avenue',79,88,'North Island','WA','49599');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (399,'Et Avenue',368,439,'CA','UP','74542');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (400,'n Av.',445,980,'North Island','IL','08706');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (401,'P.O.Sem. Av.',345,932,'RM','Katsina','82951');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (402,'st. Road',489,137,'O','Istanbul','61104');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (403,'s, Av.',294,462,'Zeeland','HE','04796');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (404,'Ap Cras Ave',550,416,'VT','W','16');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (405,'P.O.Fringilla St.',118,699,'NewfoundlandLabrador','Wisconsin','7016');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (406,'Ap Lacus. Rd.',344,308,'Van','Biobio','D40ZR');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (407,'treet',247,944,'San Jose','Ontario','01182');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (408,'Fermentum Rd.',179,375,'Cartago','Arkansas','1435H');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (409,'ctetuer, Road',482,231,'Gaz','Mazowieckie','09');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (410,'Est, Ave',207,656,'ZP','ON','14363');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (411,'P.O.Sem Street',582,939,'West Lothian','North Island','13847');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (412,'in St.',682,115,'AB','KA','21115');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (413,'Ap Dolor Rd.',481,201,'Valparaiso','NI','0843');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (414,'Ap Adipiscing St.',278,610,'Emilia-Romagna','IN','7323J');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (415,'venue',951,522,'TOS','Alaska','V94DP');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (416,'. Av.',220,196,'Istanbul','Zeeland','15239');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (417,'Consectetuer Avenue',526,742,'VII','DE','48984');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (418,'Ap Ut Road',41,777,'VIC','Galicia','3459');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (419,'Ap Ut St.',815,334,'Somerset','Ontario','93675');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (420,'Box Lacinia St.',849,758,'Zeeland','LOM','YX8Y1');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (421,'Ap Et St.',739,646,'Wie','E','18189');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (422,'Avenue',458,36,'AN','Andalucia','P39KB');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (423,'P.O.Eleifend St.',526,210,'RF','Coquimbo','84189');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (424,'Velit Rd.',640,295,'Diy','LU','7431L');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (425,'m Rd.',979,236,'Mississippi','CE','5927');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (426,' St.',335,831,'Ist','DE','Q21HZ');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (427,'Suspendisse Rd.',45,6,'Ada','QC','73640');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (428,'rna. Road',416,66,'Wie','Osun','4187F');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (429,'Quisque St.',225,643,'AN','HH','70407');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (430,'n Rd.',635,675,'Connacht','Languedoc-Roussillon','77277');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (431,'St.',716,488,'MecklenburVorpommern','QC','08182');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (432,'Ad St.',101,290,'OX','Sicilia','9694');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (433,'P.O.Suspendisse Ave',425,199,'Noord Holland','PD','07760');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (434,'P.O.on, Ave',700,115,'Pernambuco','Małopolskie','8687L');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (435,'ortis St.',92,691,'Brecknockshire','WA','6729');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (436,'P.O.Mi St.',9,81,'Wigtownshire','Parana','YG1T5');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (437,'P.O.Eu, Avenue',417,78,'Devon','Wie','5334');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (438,'Per Av.',933,560,'HU','Lower Saxony','53595');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (439,'Non Road',148,136,'Arkansas','Kansas','5437');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (440,'Nec, Road',439,896,'LAZ','SJ','75355');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (441,'Ap Orci, Ave',979,922,'NorthwestTerritories','Zeeland','14468');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (442,'Box Duis Avenue',532,782,'Wie','Catalunya','44032');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (443,'us Rd.',37,778,'Durham','Rajasthan','34264');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (444,'P.O.Dolor. Rd.',89,434,'Opolskie','EX','60505');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (445,'i, Avenue',607,503,'C','PO','I23GW');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (446,'Ap Dui, St.',626,79,'Biobio','Parana','04693');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (447,'Auctor, Rd.',100,843,'CE','Maule','9190');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (448,'P.O.Duis Rd.',831,523,'North Island','Jonkopings lan','7611');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (449,'P.O.Nec Av.',757,345,'Comunitat Valenciana','Yukon','98249');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (450,'Eu Rd.',702,54,'G','PB','38431');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (451,'Ap Congue Ave',714,91,'MA','MetropolitanSantiago','31930');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (452,'c St.',144,282,'Vienna','BW','8057');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (453,'Ap Interdum Av.',728,346,'SN','Vienna','05255');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (454,'P.O.A, Street',263,286,'South Island','SA','68198');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (455,'Ap Fringilla Street',102,595,'N.','BE','4586');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (456,'Box Tellus. Rd.',577,641,'Waals-Brabant','CH','P35ZK');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (457,'n Ave',839,210,'RS','Alberta','93');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (458,'Ap Eget Avenue',877,45,'Bahia','H','68806');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (459,'Ap Malesuada Ave',709,549,'BY','AB','74926');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (460,'suada St.',157,329,'British Columbia','H','73003');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (461,'Elit St.',627,100,'ON','Stockholms lan','KA5CZ');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (462,'P.O.Nunc Rd.',357,814,'BC','SI','88743');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (463,'c Av.',75,437,'QC','Bahia','54198');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (464,'P.O.Vulputate Street',942,770,'SO','KA','8890');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (465,'Ap Blandit St.',354,31,'VII','Van','9769');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (466,'rdum Road',909,440,'Sicilia','CO','7485');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (467,'P.O.Fusce Avenue',710,706,'A','AK','12423');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (468,'Quis Street',833,982,'WA','TN','81588');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (469,'re, Street',10,868,'Dr','Lagos','55872');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (470,'P.O.Nisi Av.',657,960,'G','OV','26409');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (471,'Quis Avenue',431,56,'Nova Scotia','Kon','70');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (472,'retra St.',271,559,'Canarias','EX','8210');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (473,'Ap Odio, St.',486,610,'Quebec','LD','33375');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (474,'ibero Ave',60,237,'Mazowieckie','ON','73219');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (475,'Ap Pharetra Street',708,518,'LOM','Lancashire','33993');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (476,'Ap Ornare. Street',376,373,'ostergotlands lan','KS','41296');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (477,'Box ictum. Road',73,126,'U','British Columbia','BW4L1');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (478,'Nam Rd.',675,766,'NI','MA','6571');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (479,'Ap Justo Rd.',966,765,'Veneto','AN','79485');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (480,'In Av.',22,736,'HH','NI','92586');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (481,'Ap Dolor. Road',576,819,'Wie','Veneto','6818K');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (482,'Ap Risus. Road',361,16,'Centre','Gaziantep','8300');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (483,'treet',192,812,'Swiętokrzyskie','Bauchi','58430');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (484,'od Road',641,500,'MA','Ontario','7354');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (485,'Ap Ante Street',234,151,'San Jose','NI','33283');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (486,'P.O.Morbi Avenue',419,610,'AN','Antofagasta','4271');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (487,'stas. Rd.',993,352,'Saskatchewan','SIC','71419');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (488,'Vitae, Road',66,844,'Munster','G','78887');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (489,'icies Rd.',175,454,'L','Diy','40519');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (490,'ibulum Ave',696,593,'Bur','N.','65423');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (491,'a Street',871,849,'HE','Madrid','96205');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (492,'em Avenue',568,829,'North Island','Gelderland','73671');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (493,'e Road',806,348,'Leinster','VIC','2737');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (494,'stie Av.',312,351,'Uttar Pradesh','Waals-Brabant','31069');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (495,'um Avenue',154,209,'Podlaskie','Bihar','62424');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (496,'Massa. St.',835,53,'Arkansas','South Island','22490');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (497,'Ap Quis Street',801,393,'Picardie','Ist','32634');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (498,'Ap Velit. Rd.',375,878,'PR','E','21886');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (499,'Arcu. Rd.',707,400,'QC','Comunitat Valenciana','8814');
INSERT INTO Direccion (id_direccion,calle,numero_ext,numero_int,colonia,ciudad,CP) VALUES (500,'Ap Tempus Av.',520,49,'KN','Victoria','40606');
