INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('tellus.eu.augue@vitaealiquet.com',5220,'cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula',233);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Proin.sed.turpis@cursusnonegestas.org',5240,'et, magna.',410);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('euismod@a.org',5260,'ac mattis velit justo nec ante. Maecenas mi felis, adipiscing',236);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('orci.sem@Duis.com',5280,'vel quam dignissim pharetra. Nam ac nulla.',581);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('malesuada.vel@consequatlectussit.edu',5300,'arcu ac orci. Ut semper pretium neque. Morbi',459);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('adipiscing@imperdietornareIn.org',5320,'nibh vulputate mauris sagittis placerat. Cras',12);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('dolor@dolor.co.uk',5340,'a, dui.',646);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('magna.et@musAeneaneget.org',5360,'ante bibendum ullamcorper. Duis cursus, diam',325);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ut@eleifendCras.net',5380,'cursus',472);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('hendrerit@magnisdisparturient.edu',5400,'neque tellus, imperdiet non, vestibulum nec, euismod in,',442);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('nibh@sapienNunc.com',5420,'sagittis lobortis mauris. Suspendisse aliquet molestie',128);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ut.eros.non@nonantebibendum.com',5440,'ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent',813);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('accumsan.laoreet@pede.edu',5460,'lorem ipsum sodales purus, in molestie tortor nibh sit',176);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Suspendisse.non.leo@blandit.org',5480,'non enim commodo',627);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Donec@quistristiqueac.co.uk',5500,'elit. Aliquam auctor, velit eget laoreet posuere,',172);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('mauris.Suspendisse@Suspendissecommodo.net',5520,'convallis est, vitae sodales nisi',727);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('quis.pede@molestiesodalesMauris.com',5540,'ultrices a, auctor non, feugiat',14);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('parturient.montes.nascetur@dolordolortempus.org',5560,'eu, eleifend nec, malesuada ut,',646);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('sociis@Quisquenonummy.com',5580,'senectus et netus et malesuada fames ac turpis',951);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('enim.mi@nonsapien.ca',5600,'eget ipsum. Suspendisse sagittis.',278);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('eget.tincidunt@diam.edu',5620,'iaculis, lacus',729);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('arcu@arcuvelquam.ca',5640,'gravida. Praesent eu nulla',599);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Nunc.quis.arcu@at.org',5660,'turpis. Nulla aliquet. Proin velit. Sed malesuada augue',463);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('convallis@Sed.org',5680,'Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra',566);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('gravida@ornare.com',5700,'eu dolor',397);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ultricies@tincidunt.com',5720,'euismod mauris eu elit. Nulla facilisi. Sed neque. Sed',72);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Aliquam.ultrices.iaculis@idantedictum.edu',5740,'eget lacus. Mauris non dui nec urna suscipit nonummy.',694);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('orci@sagittislobortismauris.ca',5760,'eu dolor egestas rhoncus. Proin nisl',703);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Mauris.quis@euodiotristique.co.uk',5780,'vulputate, posuere vulputate,',227);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Proin@Quisqueporttitor.edu',5800,'Quisque purus sapien, gravida non, sollicitudin',359);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('in@quistristiqueac.ca',5820,'arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec',405);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ultricies@odiosempercursus.ca',5840,'placerat, orci lacus vestibulum lorem, sit amet ultricies',82);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('inceptos.hymenaeos@tellusPhaselluselit.org',5860,'leo. Morbi neque tellus, imperdiet non, vestibulum',317);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('mattis.velit@imperdiet.net',5880,'rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac',180);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('risus.Duis.a@sociis.net',5900,'rhoncus. Proin nisl',969);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('non.lobortis@dictumauguemalesuada.ca',5920,'dictum cursus. Nunc mauris elit, dictum eu, eleifend nec,',861);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('sed@Maurisvestibulum.com',5940,'pellentesque,',890);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('erat.in.consectetuer@nibhenimgravida.co.uk',5960,'Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna.',469);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Mauris.ut.quam@Aliquamvulputateullamcorper.ca',5980,'diam vel arcu. Curabitur ut odio',673);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('tellus@acarcu.org',6000,'orci tincidunt adipiscing. Mauris molestie pharetra nibh.',373);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('risus.Donec@nonnisi.co.uk',6020,'enim. Nunc ut erat. Sed nunc est, mollis non,',557);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('natoque@egetmetuseu.co.uk',6040,'Suspendisse tristique neque',979);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('In.scelerisque@acfermentum.net',6060,'scelerisque neque. Nullam nisl. Maecenas',378);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('lectus.pede@pedeblanditcongue.co.uk',6080,'ipsum ac mi eleifend',739);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('aliquet.lobortis@egetipsumSuspendisse.com',6100,'et arcu imperdiet ullamcorper.',780);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('accumsan.laoreet@elit.co.uk',6120,'eu enim. Etiam imperdiet dictum magna.',606);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ac.nulla.In@nonummy.net',6140,'enim nec',567);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Nunc.lectus.pede@dapibusrutrumjusto.edu',6160,'a mi fringilla mi',391);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('laoreet.posuere.enim@congueIn.org',6180,'malesuada. Integer id magna et ipsum cursus',434);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('dictum@nuncsed.org',6200,'tempor bibendum. Donec felis',492);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('pharetra@eu.ca',6220,'Aenean',365);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('primis.in@necligula.ca',6240,'Cum sociis natoque',318);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Duis@eu.co.uk',6260,'velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum',138);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('nunc.sit.amet@eleifendvitaeerat.edu',6280,'in, dolor. Fusce feugiat. Lorem',922);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('egestas@nostraper.edu',6300,'vel pede',746);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('turpis@elitelitfermentum.ca',6320,'Fusce mollis. Duis sit',471);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('vulputate.ullamcorper@felis.co.uk',6340,'Quisque nonummy ipsum non arcu. Vivamus sit amet',555);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('turpis@risusatfringilla.org',6360,'Mauris nulla. Integer urna. Vivamus',306);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('mattis.semper.dui@cubiliaCuraeDonec.co.uk',6380,'Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet',742);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('leo@primisin.net',6400,'auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi.',34);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('gravida.Aliquam@liberomaurisaliquam.ca',6420,'eu dui. Cum sociis natoque penatibus et',259);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('pede.nonummy.ut@Mauris.org',6440,'feugiat metus sit amet ante. Vivamus',1);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('libero.Morbi@acsem.com',6460,'fermentum vel, mauris. Integer sem elit,',346);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('velit.Quisque.varius@pharetraNamac.ca',6480,'porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin',578);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('consectetuer@ultriciesdignissimlacus.com',6500,'magnis dis parturient montes, nascetur',639);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('fames@Aeneaneget.ca',6520,'facilisis',445);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('faucibus@Donecsollicitudinadipiscing.ca',6540,'nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse',867);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('sit.amet.risus@dignissimmagnaa.org',6560,'Nunc mauris sapien, cursus in, hendrerit consectetuer,',8);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('lorem@ametconsectetueradipiscing.co.uk',6580,'pharetra sed,',93);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('turpis.In.condimentum@urna.com',6600,'et arcu imperdiet ullamcorper. Duis at',408);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ac@nonummyacfeugiat.ca',6620,'placerat, orci lacus vestibulum lorem, sit',969);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Nunc.ullamcorper@estvitae.ca',6640,'sociis natoque penatibus et magnis dis parturient montes,',578);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('mus@Nam.ca',6660,'Curabitur vel lectus. Cum sociis natoque penatibus et',602);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('lorem.lorem@afeugiat.ca',6680,'dui. Cum sociis natoque penatibus et',82);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('molestie@Nunc.edu',6700,'mollis',502);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Fusce@ante.edu',6720,'justo.',279);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('velit@eu.ca',6740,'nisi dictum',347);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('dui@atpedeCras.net',6760,'dolor elit, pellentesque a, facilisis',493);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('volutpat.ornare@diamnuncullamcorper.org',6780,'eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam',422);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('tristique.pharetra@volutpat.co.uk',6800,'feugiat placerat velit. Quisque varius. Nam',108);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('vel@euarcu.net',6820,'nec urna et arcu imperdiet ullamcorper.',811);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ultricies@Proinegetodio.co.uk',6840,'aliquet. Phasellus fermentum convallis ligula. Donec luctus',23);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('convallis@tempusscelerisque.ca',6860,'non, lacinia at, iaculis quis, pede. Praesent eu dui.',633);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ultrices@Nuncpulvinar.ca',6880,'montes, nascetur ridiculus mus. Donec dignissim',436);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('erat@ultrices.edu',6900,'cursus. Nunc',578);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('urna@arcuVestibulum.net',6920,'pede. Suspendisse dui. Fusce',542);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('mus@nectempus.co.uk',6940,'Proin vel nisl. Quisque fringilla',149);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('malesuada.malesuada@nequevenenatislacus.net',6960,'Duis elementum, dui quis',132);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('In.nec.orci@euismodenimEtiam.co.uk',6980,'tempor diam dictum sapien.',445);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ullamcorper@libero.edu',7000,'nec urna',335);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ornare.lectus.ante@Maecenasmi.org',7020,'posuere cubilia',531);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('et.malesuada@ipsum.edu',7040,'volutpat. Nulla dignissim. Maecenas ornare',584);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('amet@Sedegetlacus.com',7060,'blandit. Nam nulla magna,',127);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('posuere@rutrumnon.ca',7080,'id, mollis nec, cursus a,',711);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Cras.interdum.Nunc@Nullam.net',7100,'lorem, sit amet',26);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('vulputate.posuere@nisl.edu',7120,'et',29);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('feugiat.non.lobortis@neceleifend.com',7140,'accumsan sed,',967);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('eget.ipsum@laoreetposuereenim.co.uk',7160,'Fusce',466);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('vel.arcu@risusQuisque.co.uk',7180,'consequat nec,',666);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ac.nulla@amet.ca',7200,'sed orci lobortis augue scelerisque mollis.',599);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('odio@aenim.org',5220,'nunc nulla vulputate dui, nec tempus mauris erat eget',918);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Aenean@acnullaIn.co.uk',5240,'purus. Duis elementum, dui quis',4);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('semper.cursus@Aliquam.net',5260,'adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras',502);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Sed.et.libero@orcilobortisaugue.co.uk',5280,'nascetur ridiculus mus. Donec dignissim',127);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('at.egestas@Phasellusataugue.co.uk',5300,'vel pede blandit congue. In',146);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('bibendum@egestasFuscealiquet.net',5320,'fringilla mi lacinia',616);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('commodo@lectusjustoeu.ca',5340,'mauris elit, dictum eu,',194);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('neque@necimperdietnec.com',5360,'Proin eget odio. Aliquam vulputate ullamcorper',990);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('amet.consectetuer.adipiscing@Donec.net',5380,'ullamcorper eu, euismod ac, fermentum',711);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('dis.parturient@ultricesVivamusrhoncus.org',5400,'Donec tincidunt. Donec vitae erat vel pede blandit congue.',821);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('erat@enimMauris.org',5420,'augue porttitor interdum. Sed auctor odio a purus.',18);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Curabitur.sed.tortor@aliquamarcu.com',5440,'urna. Nullam lobortis quam a',647);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('natoque.penatibus@nibhAliquamornare.ca',5460,'elit. Etiam laoreet, libero et tristique pellentesque,',803);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('in.dolor.Fusce@pellentesque.edu',5480,'sit amet nulla. Donec non',172);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('blandit@velitAliquamnisl.co.uk',5500,'Cum sociis natoque penatibus et magnis dis parturient',503);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('amet@lectusasollicitudin.com',5520,'Donec',584);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ipsum.sodales.purus@luctussit.co.uk',5540,'volutpat. Nulla dignissim. Maecenas',854);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('diam@utnisi.com',5560,'Donec fringilla.',21);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('consectetuer@Mauris.net',5580,'lorem. Donec elementum, lorem ut aliquam',484);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('fermentum@iaculisaliquet.net',5600,'nisi magna sed dui. Fusce aliquam, enim',226);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('viverra@eu.edu',5620,'varius ultrices, mauris ipsum porta elit, a',611);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('justo@mauriserateget.edu',5640,'Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.',603);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Aenean.gravida@justo.com',5660,'diam. Pellentesque habitant morbi tristique senectus et netus',855);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('eu.dolor.egestas@senectusetnetus.net',5680,'per',198);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Vestibulum.accumsan@Phaselluslibero.edu',5700,'Etiam ligula tortor, dictum eu, placerat eget,',325);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('interdum.feugiat.Sed@ametdiam.ca',5720,'malesuada fames ac turpis egestas. Aliquam fringilla cursus purus.',618);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('blandit@noncursus.edu',5740,'eros nec tellus. Nunc lectus pede, ultrices',877);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('dui.nec.urna@estac.ca',5760,'lacinia. Sed congue, elit sed consequat auctor,',474);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('aliquam.eros@urnaNunc.org',5780,'nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus',10);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('justo@eudui.co.uk',5800,'mauris eu elit. Nulla facilisi. Sed neque. Sed',385);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('commodo.auctor@laoreet.org',5820,'pede ac urna. Ut tincidunt vehicula risus. Nulla',203);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('libero.nec.ligula@sociosquadlitora.co.uk',5840,'amet ante. Vivamus non',351);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('non.dui@estvitaesodales.com',5860,'tempor erat neque non quam.',978);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Duis.risus.odio@diamPellentesque.net',5880,'nascetur ridiculus mus. Donec dignissim magna',762);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Sed@eleifend.com',5900,'dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor',108);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('non@vitaeerat.org',5920,'risus. Nunc',982);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('turpis.nec@Craseu.com',5940,'egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem',813);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('magna.a@egetmassa.com',5960,'leo. Morbi neque',583);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('nonummy.ultricies@cursusNunc.co.uk',5980,'aliquet libero. Integer',378);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('faucibus@nuncQuisqueornare.edu',6000,'vehicula. Pellentesque tincidunt',865);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('accumsan.interdum.libero@euaugue.edu',6020,'lacus. Quisque',989);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('eu.dolor@enimEtiamimperdiet.com',6040,'Mauris magna.',48);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('aliquam@ipsum.com',6060,'Vivamus non lorem vitae',24);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('mollis@id.co.uk',6080,'quis turpis vitae',982);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('at.velit@iaculisnec.ca',6100,'semper tellus',985);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('sagittis.Nullam@maurisMorbi.co.uk',6120,'congue, elit sed consequat auctor, nunc nulla vulputate',225);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('quam.vel.sapien@vellectusCum.edu',6140,'Phasellus dolor elit, pellentesque a, facilisis',117);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('sed.sapien.Nunc@bibendumullamcorperDuis.net',6160,'massa. Mauris',775);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Aenean.gravida.nunc@tempor.edu',6180,'elit',3);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('libero@malesuadafringillaest.com',6200,'dui nec urna suscipit',667);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('augue.porttitor@sed.com',6220,'amet nulla. Donec non justo.',420);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('vel.mauris@convallisconvallis.co.uk',6240,'nibh lacinia orci, consectetuer',595);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('neque.pellentesque@atvelitPellentesque.co.uk',6260,'vitae nibh. Donec est mauris,',281);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('urna.et@acmattis.co.uk',6280,'elit, pharetra ut, pharetra',86);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ipsum.nunc@risus.org',6300,'leo. Morbi neque tellus, imperdiet non, vestibulum',236);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('facilisis.vitae.orci@netuset.net',6320,'erat, eget tincidunt dui augue eu tellus.',221);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('magna@risusMorbimetus.net',6340,'ullamcorper, velit in aliquet',842);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Donec.tempor@est.co.uk',6360,'Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra.',754);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Duis@etmagnisdis.edu',6380,'Duis sit',303);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ante.lectus@loremluctusut.net',6400,'vitae semper egestas, urna justo faucibus lectus,',646);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('et.euismod@Proinvel.com',6420,'blandit at, nisi. Cum sociis',829);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ornare.lectus@nequenon.edu',6440,'porttitor interdum.',328);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('odio.sagittis.semper@Maurisnondui.com',6460,'viverra. Donec',563);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Integer@accumsan.org',6480,'purus sapien, gravida non, sollicitudin a, malesuada',223);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('In.at@temporloremeget.edu',6500,'Proin',554);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('pede.blandit.congue@massaSuspendisseeleifend.net',6520,'eget laoreet posuere, enim nisl elementum purus, accumsan interdum',280);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('et@feugiattellus.co.uk',6540,'consectetuer adipiscing elit.',875);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('orci@vitaeodio.edu',6560,'imperdiet dictum magna. Ut tincidunt',882);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('aliquam@nasceturridiculusmus.com',6580,'odio. Aliquam vulputate ullamcorper magna. Sed eu',767);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('netus@erosProinultrices.ca',6600,'litora torquent per conubia nostra, per inceptos hymenaeos. Mauris',815);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Mauris.ut@mauris.edu',6620,'enim nec tempus scelerisque, lorem',934);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('tempor@Maecenas.org',6640,'dui, in sodales',985);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('a@ullamcorpereueuismod.co.uk',6660,'quis lectus. Nullam suscipit, est',276);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('mattis@Vivamusnibhdolor.com',6680,'eu augue porttitor interdum.',54);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('mauris.aliquam@gravidasit.org',6700,'luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis.',793);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('nunc@miloremvehicula.ca',6720,'facilisis, magna',705);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('eros.turpis.non@sit.net',6740,'Nullam velit dui, semper et, lacinia vitae,',666);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('risus.Quisque.libero@magnatellusfaucibus.net',6760,'lacus vestibulum',641);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('vitae.risus@auctor.edu',6780,'Mauris blandit',377);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('commodo.at@tortor.co.uk',6800,'amet',718);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('neque.In@ullamcorpernislarcu.net',6820,'Mauris',604);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Proin.vel.nisl@posuere.net',6840,'tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque',51);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('a.ultricies@semmolestiesodales.com',6860,'fringilla purus mauris',795);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('montes.nascetur.ridiculus@tellusPhasellus.net',6880,'Vivamus',220);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Fusce@Duissitamet.edu',6900,'vel pede',874);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('dui.semper@Craseutellus.co.uk',6920,'odio sagittis semper. Nam tempor diam',127);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('et@nibh.net',6940,'nec',834);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('arcu@CuraePhasellus.net',6960,'eu augue porttitor interdum. Sed auctor odio a purus. Duis',394);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ornare.lectus@venenatislacus.org',6980,'ac mattis velit justo nec ante. Maecenas mi felis,',235);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('facilisis.lorem.tristique@magnaSuspendisse.com',7000,'montes, nascetur ridiculus',626);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('velit.in.aliquet@velitdui.net',7020,'ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi',42);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ante.Nunc@velitQuisque.net',7040,'at lacus. Quisque purus sapien, gravida non,',887);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Donec.nibh.enim@placeratorci.net',7060,'eleifend, nunc risus',128);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('nunc.sed@sempererat.com',7080,'auctor',99);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Fusce.fermentum.fermentum@massanonante.edu',7100,'Aliquam ultrices',965);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('quis.diam@nondapibus.org',7120,'in consequat enim diam vel arcu. Curabitur ut odio vel',469);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('molestie.Sed.id@Pellentesque.co.uk',7140,'orci. Ut',291);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('Praesent.eu@justoeu.net',7160,'Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel,',236);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('lacus.vestibulum.lorem@egestaslaciniaSed.co.uk',7180,'turpis egestas.',932);
INSERT INTO Cliente (email,num_cuenta,contrasenia,puntos_acumulados) VALUES ('ligula.consectetuer@consectetuermauris.ca',7200,'ultrices. Duis',242);
