INSERT INTO Salsa (id_alimento,picor) VALUES (1,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (2,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (3,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (4,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (5,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (6,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (7,'Mucho');
INSERT INTO Salsa (id_alimento,picor) VALUES (8,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (9,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (10,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (11,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (12,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (13,'Mucho');
INSERT INTO Salsa (id_alimento,picor) VALUES (14,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (15,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (16,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (17,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (18,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (19,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (20,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (21,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (22,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (23,'Mucho');
INSERT INTO Salsa (id_alimento,picor) VALUES (24,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (25,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (26,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (27,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (28,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (29,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (30,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (31,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (32,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (33,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (34,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (35,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (36,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (37,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (38,'Mucho');
INSERT INTO Salsa (id_alimento,picor) VALUES (39,'Poco');
INSERT INTO Salsa (id_alimento,picor) VALUES (40,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (41,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (42,'Mucho');
INSERT INTO Salsa (id_alimento,picor) VALUES (43,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (44,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (45,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (46,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (47,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (48,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (49,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (50,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (51,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (52,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (53,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (54,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (55,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (56,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (57,'Poco');
INSERT INTO Salsa (id_alimento,picor) VALUES (58,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (59,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (60,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (61,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (62,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (63,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (64,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (65,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (66,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (67,'Mucho');
INSERT INTO Salsa (id_alimento,picor) VALUES (68,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (69,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (70,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (71,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (72,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (73,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (74,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (75,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (76,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (77,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (78,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (79,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (80,'Mucho');
INSERT INTO Salsa (id_alimento,picor) VALUES (81,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (82,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (83,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (84,'Poco');
INSERT INTO Salsa (id_alimento,picor) VALUES (85,'Mucho');
INSERT INTO Salsa (id_alimento,picor) VALUES (86,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (87,'Dulce');
INSERT INTO Salsa (id_alimento,picor) VALUES (88,'Poco');
INSERT INTO Salsa (id_alimento,picor) VALUES (89,'Moderado');
INSERT INTO Salsa (id_alimento,picor) VALUES (90,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (91,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (92,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (93,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (94,'Excesivo');
INSERT INTO Salsa (id_alimento,picor) VALUES (95,'Mucho');
INSERT INTO Salsa (id_alimento,picor) VALUES (96,'Alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (97,'Muy alto');
INSERT INTO Salsa (id_alimento,picor) VALUES (98,'Muchisimo');
INSERT INTO Salsa (id_alimento,picor) VALUES (99,'Nada');
INSERT INTO Salsa (id_alimento,picor) VALUES (100,'Muchisimo');
